name: Playwright C# Tests

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Install Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Install Playwright Browsers
        run: playwright install

      - name: Run tests
        run: dotnet test --configuration Release --settings test.runsettings

  notify-success:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: ✅ Notify on Success
        run: echo "✅ Playwright C# Tests Passed on main branch!"

  notify-failure:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: ❌ Notify on Failure
        run: echo "❌ Playwright C# Tests Failed on main branch!"
